version: '3.1'

services:

  db:
    image: mysql
    container_name: online-shop-mysql-conteiner
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_USER: "root"
    ports:
    - "3306:3306"
